config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/signup_user', to: 'users#new'
  post '/signup_user', to: 'users#create'
  post '/farm_data', to: 'hall_detail#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :assignments

  validates :name,
            presence: true,
            uniqueness: {case_sensitive: false}

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :farm
  has_many :assignments, dependent: :delete_all
  has_many :roles, through: :assignments
  accepts_nested_attributes_for :assignments

  attr_accessor :remember_token, :activation_token
  has_secure_password

  before_save :downcase_email
  before_save :downcase_name
  before_create :create_activation_digest


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,
            presence: true,
            length: { maximum: 50 },
            uniqueness: { case_sensitive: false }

  validates :email,
            presence: true,
            length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: { case_sensitive: false }

  validates :password,
            presence: true,
            length: {minimum: 6},
            allow_nil: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def role?(role)
    roles.any? {|r| r.name.underscore.to_sym == role}
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_farm_info_email(death_info, hatch_info)
    FarmMailer.farm_information(self, death_info, hatch_info).deliver_now
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def downcase_name
    self.name = name.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      flash[:success] = "Account activated! Now you can log in."
      redirect_to login_url
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/hall_detail_controller.rb
class HallDetailController < ApplicationController

  def create
    turkey_death_data = params[:death]
    turkey_hatch_data = params[:hatch]
    @user = User.find(params[:id])
    @user.send_farm_info_email(turkey_death_data, turkey_hatch_data)
    redirect_to @user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in(user)
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or(user)
      else
        message = "Account not activated. Check your email for activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = "Invalid name/password combination"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show, :index, :destroy]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only: [:destroy, :index, :create, :new]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @halls = @user.farm.halls
    redirect_to root_url unless @user.activated?
  end

  def create
    @user = User.new(user_params)
    User.transaction do
      if (@user.save)
        @user.assignments.first_or_create!(user_id: @user.id, role_id: Role::REGULAR_USER) #test na validaciu ci kazdy user bude mat rolu
        @user.send_activation_email
        flash[:info] = "Please check your email to activate your account."
        redirect_to root_url
      else
        render 'new'
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Zmeny boli uložené."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

  def correct_user
    user = User.find_by(id: params[:id])
    redirect_to current_user unless current_user?(user)
  end

  def admin_user
    if !logged_in?
      flash[:warning] = "Please, contact adming to registrate you."
      redirect_to home_path
    elsif !current_user.role?(:admin)
      flash[:info] = "Only admin can view this page."
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hall_detail_helper.rb
module HallDetailHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in(user)
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/turkey_data_helper.rb
module TurkeyDataHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/farm/_farm_info.html.erb
<%= form_tag(farm_data_path(id: current_user), id: 'farm-form') do %>

    <h2>úhyny na každú halu</h2>
    <%= fields_for :death do |builder| %>
        <%= builder.fields_for :halls do |b| %>
            <% (1..@halls).each do |hall_index| %>
                <%= b.number_field "#{hall_index}", class: 'form-control', placeholder: "Hala #{hall_index}" %>
            <% end %>
        <% end %>
        <%= builder.text_area :comment, class: 'form-control', :rows => 4, :cols => 50, placeholder: 'Komentár...' %>
    <% end %>

    <h2>znáška na každú halu</h2>
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 text-center farm-form-text">
        V hrubom:
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 text-center farm-form-text">
        V čistom:
      </div>
    </div>
    <%= fields_for :hatch do |builder| %>
        <%= builder.fields_for :halls do |b| %>
            <% (1..@halls).each do |hall_index| %>
                <%= b.fields_for "#{hall_index}" do |f| %>
                    <div class="row">
                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <%= f.number_field "raw", class: 'form-control', placeholder: "Hala #{hall_index}" %>
                      </div>
                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <%= f.number_field "sorted", class: 'form-control', placeholder: "Hala#{hall_index}" %>
                      </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <%= builder.text_area :comment, class: 'form-control', :rows => 4, :cols => 50, placeholder: 'Komentár...' %>
    <% end %>

    <%= submit_tag "Odoslať", class: "btn btn-primary" %>
<% end %>

app/views/farm/_form.html.erb
<%= form_tag(farm_data_path(id: current_user), id: 'farm-form') do %>

    <h2>úhyny na každú halu</h2>
    <%= fields_for :death do |builder| %>
        <%= builder.fields_for :halls do |b| %>
            <% (1..@halls).each do |hall_index| %>
                <%= b.number_field "#{hall_index}", class: 'form-control', placeholder: "Hala #{hall_index}" %>
            <% end %>
        <% end %>
        <%= builder.text_area :comment, class: 'form-control', :rows => 4, :cols => 50, placeholder: 'Komentár...' %>
    <% end %>

    <h2>znáška na každú halu</h2>
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 text-center farm-form-text">
        V hrubom:
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 text-center farm-form-text">
        V čistom:
      </div>
    </div>
    <%= fields_for :hatch do |builder| %>
        <%= builder.fields_for :halls do |b| %>
            <% (1..@halls).each do |hall_index| %>
                <%= b.fields_for "#{hall_index}" do |f| %>
                    <div class="row">
                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <%= f.number_field "raw", class: 'form-control', placeholder: "Hala #{hall_index}" %>
                      </div>
                      <div class="col-xs-6 col-sm-6 col-md-6">
                        <%= f.number_field "sorted", class: 'form-control', placeholder: "Hala#{hall_index}" %>
                      </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
        <%= builder.text_area :comment, class: 'form-control', :rows => 4, :cols => 50, placeholder: 'Komentár...' %>
    <% end %>

    <%= submit_tag "Odoslať", class: "btn btn-primary" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  Copyright © 2017, MGroup, Všetky práva vyhradené.
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-brand-centered">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to home_path, class: 'navbar-brand-centered' do %>
            <%= image_tag("logo2.png", alt: "logo", id: 'logo-image') %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-brand-centered">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
              <li class="active">
                <%= link_to current_user do %>
                    <span class="glyphicon glyphicon-home"></span>
                    Domov
                <% end %>
              </li>
              <% if current_user.role?(:admin) %>
                  <li>
                    <%= link_to users_path do %>
                        <span class="glyphicon glyphicon-list-alt"></span>
                        Používatelia
                    <% end %>
                  </li>
              <% end %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><span
              class="glyphicon glyphicon-user"></span><%= current_user.name.capitalize %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to edit_user_path(current_user) do %>
                        <span class="glyphicon glyphicon-cog"></span>
                        Nastavenia
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to logout_path, method: :delete do %>
                        <span class="glyphicon glyphicon-off"></span>
                        Odhlásiť sa
                    <% end %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li>
                <%= link_to login_path do %>
                    <span class="glyphicon glyphicon-log-in"></span>
                    Prihlásiť sa
                <% end %>
              </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= render 'layouts/rails_defaults' %>
  <%= render 'layouts/shim' %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Úvod") %>
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_user_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/users/_user.html.erb
<% if !current_user?(user) %>
    <div class="row">
      <%#= gravatar_for user, size: 50 %>
      <div class="col-xs-3 col-xs-offset-1 col-sm-3 col-sm-offset-1 col-md-3 col-md-offset-1">
        <%= user.name %>
      </div>
      <div class="col-xs-2 col-xs-offset-6 col-sm-2 col-sm-offset-6 col-md-2 col-md-offset-6">
        <%= link_to user, method: :delete,
                    data: {confirm: "You sure?"} do %>
            <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </div>
    </div>
<% end %>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name, "Meno" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "E-mail" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "Nové heslo" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Potvrďte heslo" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Uložiť zmeny", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Nastavenia") %>
<% provide(:button, "Uložiť zmeny") %>
<h1>Upraviť profil</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'user_form' %>



    <!--<div class="gravatar_edit">
      <%#= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>-->


  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Používatelia') %>
<h1>All users</h1>
<%= link_to "Vytvor užívateľa", signup_user_path, class: "btn btn-primary" %>
<ul class="users">
  <% @users.each do |user| %>
      <%= render user %>
  <% end %>

  <%= will_paginate %>

</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button, "Vytvoriť účet") %>
<h1>Registrovať sa</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Domov") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if @user.farm %>
        <h1 id="farm-title"><%= @user.farm.name %></h1>
    <% end %>
    <%= render 'farm/form' %>
  </div>
</div>